### PR TITLE
Fix install instruction

### PR DESCRIPTION
**Pull request by brorbw**

### CODE REVIEW

**Comment by kutsan** [comment]
Thanks @brorbw! Is `ZSH_CUSTOM` coming from oh-my-zsh framework? I think we should also change the `source` line (line 34) in addition to this. There is also native `ZDOTDIR` variable we should consider using.

**Comment by doronbehar** [comment]
> Thanks @brorbw! Is `ZSH_CUSTOM` coming from oh-my-zsh framework? I think we should also change the `source` line (line 34) in addition to this. There is also native `ZDOTDIR` variable we should consider using.

I agree.

**Comment by brorbw** [comment]
@kutsan I think it’s from oh-my-zsh. Let me investigate. I agree about L34

**Review by doronbehar — APPROVED** [review]

**Comment by kutsan** [comment]
Looks good to me, thanks! I think we can say that people who tweaked the `ZDOTDIR` variable should be able to figure out where to install. So we don't need to handle that case. Thanks again!

**Comment by brorbw** [comment]
I agree. I looked into `ZDOTDIR` which is unset on a default `oh-my-zsh` install so I think is a very small group of people. You are very welcome!

**Pull request merged**
