### PR TITLE
add  freebsd support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kutsan** [comment]
Thank you but I don't think we should repeat the existing code for nothing. We could have done that like this:

```diff
diff --git a/zsh-system-clipboard.zsh b/zsh-system-clipboard.zsh
--- a/zsh-system-clipboard.zsh
+++ b/zsh-system-clipboard.zsh
@@ -42,7 +42,7 @@ function _zsh_system_clipboard() {
                }
                ;;

-           linux*)
+           linux*|freebsd*)
                if (hash xclip 2>/dev/null) {
                    local clipboard_selection
```

If you can `--force` update the commit, I can merge it.

**Review by kutsan — CHANGES_REQUESTED** [review]
Instead of repeating the existing functionality, case statement needs to be changed according to my other comment.

**Comment by ghost** [comment]
We need to at least change hash to whence then. hash doesn't appear to respect path on freebsd.

**Comment by kutsan** [comment]
@gregf Are you sure? Unlike `whence`, `hash` doesn't give you an output about the path. It just gives you an exit code, `0` or `1`. I don't have a FreeBSD machine right now. Can you try editing the plugin file locally try using with `hash`?

**Comment by ghost** [comment]
You are right, not sure why I thought that the other day when I did this. Do you want me to resubmit or do you want to just add the |freebsd* yourself?

**Comment by kutsan** [comment]
Please don't open another pull request. If you can `--force` push it like I said above, I can merge it this PR.

**Comment by kutsan** [comment]
I mean commit again with `--amend` and push with `--force`.

**Review by kutsan — APPROVED** [review]

**Comment by kutsan** [comment]
Thanks again! Much appericated it.

**Pull request merged**
